name: GitProject
options:
  bundleIdPrefix: com.test.GitProject
  xcodeVersion: '12.5'
  deploymentTarget: '14.5'
  groupSortPosition: top
  generateEmptyDirectories: true
  minimumXcodeGenVersion: '2.18.0'


configs:
  Debug: debug 
  Release: release

targets:
  GitProject:
    type: application
    platform: iOS
    deploymentTarget: 14.5
    settings:
      base:
        MARKETING_VERSION: 1.0
    sources:
       - path: GitProject
         exclude: "*.xcodeproj"